networks:
  thalis-stack:
    driver: bridge
    attachable: true

services:
  comfyui:
    image: ghcr.io/thalisai/thalis-comfyui:main
    build:
      context: .
      dockerfile: containers/Dockerfile.comfyui
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['1']
    environment:
      - HF_HOME=/var/lib/hf
    networks:
      - thalis-stack
    ports:
      - "8188:8188"
    volumes:
      - ~/.thalis/data/comfyui:/var/lib/comfyui
      - ~/.thalis/data/hf:/var/lib/hf
  manager:
    image: ghcr.io/thalisai/thalis-manager:main
    networks:
      - thalis-stack
    ports:
      - "8000:8000"
    volumes:
      - ./config/manager.yaml:/opt/manager/config.yaml
      - ~/.thalis/data/comfyui:/var/lib/comfyui
      - ~/.thalis/data/manager:/var/lib/manager
  nginx:
    image: ghcr.io/thalisai/thalis-nginx:main
    build:
      context: .
      dockerfile: containers/Dockerfile.nginx
    networks:
      - thalis-stack
    ports:
      - "8001:80"
  ollama:
    image: ollama/ollama:latest # thalis/ollama
    build:
      context: .
      dockerfile: containers/Dockerfile.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0']
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_MODELS=/var/lib/ollama/models
    networks:
      - thalis-stack
    ports:
      - "11434:11434"
    volumes:
      - ~/.thalis/data/ollama:/var/lib/ollama
  open-webui:
    image: ghcr.io/thalisai/thalis-webui:thalis-main
    #build:
    #  context: .
    #  dockerfile: containers/Dockerfile.open-webui
    environment:
      - HF_HOME=/var/lib/hf
    networks:
      - thalis-stack
    ports:
      - "8080:8080"
    volumes:
      - ./config/open-webui.env:/opt/open-webui/.env
      - ~/.thalis/data/open-webui:/var/lib/open-webui
      - ~/.thalis/data/hf:/var/lib/hf
